name: Spotify Now Playing

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  spotify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Update Spotify Widget
        uses: kittinan/spotify-github-profile@master
        with:
          spotify_client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          spotify_client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          spotify_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          bar_color: E8A87C
          bar_color_cover: false

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update spotify now playing"
          file_pattern: "*.svg"
